spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${AWS_RDS_ENDPOINT}/episode1?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQL_ROOT_NAME}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    import: aws-parameterstore:/episode1/jookbiren

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}

jwt:
  secret: ${JWT_SECRET_KEY}